#!/bin/bash

if [ "$#" -lt 1 ]; then
    TAG="mavel101/dream_reco"
else
    TAG="$1"
fi

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

echo $dir
docker run --gpus all -d -t --rm --user $(id -u):$(id -g) -p 9002:9002 -v $dir:/tmp/share $TAG
